#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
rm ./app/lint-baseline.xml
echo "======================================================="
echo "post-commit File is deleted"
echo "======================================================="
